plugins: 
- rubocop-capybara
- rubocop-rails
- rubocop-rspec
- rubocop-rspec_rails

AllCops:
  NewCops: enable
  
Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
  - db/migrate/*
 
Metrics/MethodLength:
  Exclude:
  - db/migrate/*

Style/StringLiterals:
  Exclude:
  - config/importmap.rb
