require: 
- rubocop-capybara
- rubocop-rails
- rubocop-rspec
- rubocop-rspec_rails

AllCops:
  NewCops: enable
  
Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude: 
  - spec/features/**/*

RSpec/ExampleLength:
  Exclude: 
  - spec/features/**/*
